# Generated by Django 6.0.6 on 2026-07-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='sdk_session_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
