# Generated by Django 6.0.7 on 2026-07-13 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_lesson_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=512)),
                ('kind', models.CharField(max_length=32)),
                ('format', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['kind', 'path'],
            },
        ),
        migrations.AddConstraint(
            model_name='learningmaterial',
            constraint=models.UniqueConstraint(fields=('workspace', 'path'), name='unique_material_path_per_workspace'),
        ),
    ]
