# Generated by Django 6.0.7 on 2026-07-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_chatturn_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='topic_slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(fields=('user_id', 'topic_slug'), name='unique_topic_slug_per_user'),
        ),
    ]
